version: '3.5'

services:
  app:
    build: .
    command: tail -f /dev/null # keep container running
    working_dir: /apps
    environment:
      - CARGO_TARGET_DIR=/tmp/target # to avoid linker issues
    volumes:
      - .:/apps
      - rust_target:/tmp/target
    ports:
      - 3000:3000
      - 8000:8000
      - 9944:9944

volumes:
  rust_target:
